[package]
name = "doom"
version = "0.1.0"
edition = "2021"

[dependencies]
[dependencies.sdl2]
version = "0.37.0"
features = ["use-pkgconfig"]
#brew install cmake
#brew install sdl2
#export CFLAGS="-std=c99"
